version: 2
updates:
    # Maintain dependencies for GitHub Actions
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'sunday'

    # Maintain dependencies for npm
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'sunday'

    # Configuration for Dockerfile
    - package-ecosystem: 'docker'
      directory: 'apps/'
      schedule:
          interval: 'weekly'
          day: 'sunday'
