module.exports = {
    trailingComma: "all",
    tabWidth: 4,
    useTabs: false,
    semi: true,
    printWidth: 120,
    quoteProps: "as-needed",
    bracketSpacing: true,
    bracketSameLine: false,
    arrowParens: "always",
    endOfLine: "auto",
    proseWrap: "preserve",
    htmlWhitespaceSensitivity: "css",
    singleAttributePerLine: true,
};
