---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - docs-frontend-deployment.yaml
    - docs-frontend-service.yaml
images:
    - name: docs-frontend
      newName: eu.gcr.io/digdir-fdk-infra/docs-frontend
      newTag: $(GIT_COMMIT_SHA)
