---
apiVersion: v1
kind: Service
metadata:
  name: contact-form
spec:
  selector:
    app: contact-form
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
