const basePath = process.env.FDK_BASE_URI || 'http://localhost:3000';

export const paths = {
  root: `${basePath}`,
  organizations: `${basePath}/organizations`,
  tools: `${basePath}/tools`,
  forms: `${basePath}/forms`,
  dataHunter: `${basePath}/forms/data-hunter`,
  searchAll: `${basePath}/search-all`,
  datasets: `${basePath}/datasets`,
  dataServices: `${basePath}/data-services`,
  concepts: `${basePath}/concepts`,
  informationModels: `${basePath}/information-models`,
  guidance: `${basePath}/guidance`,
  reports: `${basePath}/reports`,
  about: `${basePath}/about`,
  sparql: `${basePath}/sparql`,
  aboutDatasetCatalog: `${basePath}/om-datasettkatalogen`,
  aboutConceptCatalog: `${basePath}/om-begrepskatalogen`,
  aboutInformationModelCatalog: `${basePath}/om-informasjonskatalogen`,
  aboutDataServiceCatalog: `${basePath}/om-api-katalogen`,
  aboutRegistration: `${basePath}/about-registration`,
  artificialIntelligence: `${basePath}/kunstig-intelligens`,
  requests: `${basePath}/requests`,
  accessibilityStatement: 'https://uustatus.no/nb/erklaringer/publisert/8020b962-b706-4cdf-ab8b-cdb5f480a696',
  privacyPolicy: 'https://www.digdir.no/digdir/personvernerklaering/706',
  cookies: 'https://www.digdir.no/digdir/informasjonskapsler/707',
  nationalDatacatalogEmail: 'mailto:fellesdatakatalog@digdir.no',
};
