export const paths = {
  root: `/`,
  organizations: `/organizations`,
  tools: `/tools`,
  dataHunter: `/data-hunter`,
  searchAll: `/search-all`,
  datasets: `/datasets`,
  dataServices: `/data-services`,
  concepts: `/concepts`,
  informationModels: `/information-models`,
  guidance: `/guidance`,
  reports: `/reports`,
  about: `/about`,
  sparql: `/sparql`,
  aboutDatasetCatalog: `/om-datasettkatalogen`,
  aboutConceptCatalog: `/om-begrepskatalogen`,
  aboutInformationModelCatalog: `/om-informasjonskatalogen`,
  aboutDataServiceCatalog: `/om-api-katalogen`,
  aboutRegistration: `/about-registration`,
  artificialIntelligence: `/kunstig-intelligens`,
  requests: `/requests`,
  accessibilityStatement: 'https://uustatus.no/nb/erklaringer/publisert/8020b962-b706-4cdf-ab8b-cdb5f480a696',
  privacyPolicy: 'https://www.digdir.no/digdir/personvernerklaering/706',
  cookies: 'https://www.digdir.no/digdir/informasjonskapsler/707',
  nationalDatacatalogEmail: 'mailto:fellesdatakatalog@digdir.no',
};
