export const paths = {
  root: '/',
  organizations: '/organizations',
  tools: '/tools',
  contactForm: '/contact-form',
  searchAll: '/search-all',
  datasets: '/datasets',
  dataServices: '/data-services',
  concepts: '/concepts',
  informationModels: '/information-models',
  guidance: '/guidance',
  reports: '/reports',
  about: '/about',
  aboutRegistration: '/about-registration',
  accessibilityStatement: 'https://uustatus.no/nb/erklaringer/publisert/8020b962-b706-4cdf-ab8b-cdb5f480a696',
  privacyPolicy: 'https://www.digdir.no/digdir/personvernerklaering/706',
  cookies: 'https://www.digdir.no/digdir/informasjonskapsler/707',
  nationalDatacatalogEmail: 'mailto:fellesdatakatalog@digdir.no',
};
