---
apiVersion: v1
kind: Service
metadata:
    name: frontpage-frontend
spec:
    selector:
        app: frontpage-frontend
    ports:
        - name: http
          protocol: TCP
          port: 8080
          targetPort: 8080
    type: NodePort
