---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - frontpage-frontend-deployment.yaml
    - frontpage-frontend-service.yaml
images:
    - name: frontpage-frontend
      newName: eu.gcr.io/digdir-fdk-infra/frontpage-frontend
      newTag: $(GIT_COMMIT_SHA)
