---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forms-frontend
  labels:
    app: forms-frontend
spec:
  selector:
    matchLabels:
      app: forms-frontend
  template:
    spec:
      containers:
        - name: forms-frontend
