---
apiVersion: v1
kind: Service
metadata:
  name: frontpage
spec:
  selector:
    app: frontpage
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
