---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontpage
  labels:
    app: frontpage
spec:
  selector:
    matchLabels:
      app: frontpage
  template:
    spec:
      containers:
        - name: frontpage
          env:
            - name: DATAJEGER_EMAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: fdk-smtp-staging
                  key: DATAJEGER_EMAIL_ADDRESS
            - name: FDK_MAIL_SERVICE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: fdk-smtp-staging
                  key: FDK_MAIL_SENDER_SERVICE_ENDPOINT
            - name: FDK_MAIL_SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: fdk-smtp-staging
                  key: API_KEY
            - name: FDK_REGISTRATION_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-staging
                  key: FDK_REGISTRATION_BASE_URI
            - name: FDK_COMMUNITY_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-staging
                  key: FDK_COMMUNITY_BASE_URI
            - name: FDK_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-staging
                  key: FDK_BASE_URI
