---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontpage-frontend
    labels:
        app: frontpage-frontend
spec:
    selector:
        matchLabels:
            app: frontpage-frontend
    template:
        spec:
            containers:
                - name: frontpage-frontend
                  env:                    
                      - name: FDK_REGISTRATION_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-demo
                                key: FDK_REGISTRATION_BASE_URI
                      - name: FDK_COMMUNITY_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-demo
                                key: FDK_COMMUNITY_BASE_URI
                      - name: FDK_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-demo
                                key: FDK_BASE_URI
                      - name: FDK_LLM_SEARCH_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-demo
                                key: FDK_LLM_SEARCH_BASE_URI
