---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base/frontpage-frontend
  - ingress.yaml

patchesStrategicMerge:
  - frontpage-frontend-env.yaml
