apiVersion: apps/v1
kind: Deployment
metadata:
    name: data-norge-frontend
    labels:
        app: data-norge-frontend
spec:
    selector:
        matchLabels:
            app: data-norge-frontend
    template:
        spec:
            containers:
                - name: data-norge-frontend
                  env:
                      - name: FDK_REGISTRATION_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-prod
                                key: FDK_REGISTRATION_BASE_URI
                      - name: FDK_COMMUNITY_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-prod
                                key: FDK_COMMUNITY_BASE_URI
                      - name: FDK_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-prod
                                key: FDK_BASE_URI
                      - name: FDK_DATA_NORGE_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-prod
                                key: FDK_DATA_NORGE_BASE_URI
                      - name: DATAJEGER_EMAIL_ADDRESS
                        valueFrom:
                            secretKeyRef:
                                name: fdk-smtp-prod
                                key: DATAJEGER_EMAIL_ADDRESS
                      - name: FDK_MAIL_SERVICE_ENDPOINT
                        valueFrom:
                            secretKeyRef:
                                name: fdk-smtp-prod
                                key: FDK_MAIL_SENDER_SERVICE_ENDPOINT
                      - name: FDK_MAIL_SERVICE_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: fdk-smtp-prod
                                key: API_KEY
                      - name: FDK_LLM_SEARCH_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-prod
                                key: FDK_LLM_SEARCH_BASE_URI
