---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: docs-frontend
    labels:
        app: docs-frontend
spec:
    selector:
        matchLabels:
            app: docs-frontend
    template:
        spec:
            containers:
                - name: docs-frontend
                  env:
                      - name: FDK_REGISTRATION_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-prod
                                key: FDK_REGISTRATION_BASE_URI
                      - name: FDK_COMMUNITY_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-prod
                                key: FDK_COMMUNITY_BASE_URI
                      - name: FDK_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-prod
                                key: FDK_BASE_URI
                      - name: DATA_NORGE_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-prod
                                key: DATA_NORGE_BASE_URI
