---
apiVersion: v1
kind: Service
metadata:
  name: forms-frontend
spec:
  selector:
    app: forms-frontend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
