---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - forms-frontend-deployment.yaml
  - forms-frontend-service.yaml
images:
  - name: forms-frontend
    newName: eu.gcr.io/digdir-fdk-infra/forms-frontend
    newTag: $(GIT_COMMIT_SHA)
