---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: data-norge-frontend
    labels:
        app: data-norge-frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: data-norge-frontend
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: data-norge-frontend
            annotations:
                prometheus.io/scrape: 'false'
        spec:
            containers:
                - name: data-norge-frontend
                  env:
                    - name: FDK_REGISTRATION_BASE_URI
                      valueFrom:
                          secretKeyRef:
                              name: commonurl
                              key: FDK_REGISTRATION_BASE_URI
                    - name: FDK_COMMUNITY_BASE_URI
                      valueFrom:
                          secretKeyRef:
                              name: commonurl
                              key: FDK_COMMUNITY_BASE_URI
                    - name: FDK_BASE_URI
                      valueFrom:
                          secretKeyRef:
                              name: commonurl
                              key: FDK_BASE_URI
                    - name: DATAJEGER_EMAIL_ADDRESS
                      valueFrom:
                          secretKeyRef:
                              name: fdk-smtp
                              key: DATAJEGER_EMAIL_ADDRESS
                    - name: FDK_MAIL_SERVICE_ENDPOINT
                      valueFrom:
                          secretKeyRef:
                              name: fdk-smtp
                              key: FDK_MAIL_SENDER_SERVICE_ENDPOINT
                    - name: FDK_MAIL_SERVICE_API_KEY
                      valueFrom:
                          secretKeyRef:
                              name: fdk-smtp
                              key: API_KEY
                    - name: FDK_LLM_SEARCH_BASE_URI
                      valueFrom:
                          secretKeyRef:
                              name: commonurl
                              key: FDK_LLM_SEARCH_BASE_URI
                    - name: FDK_SEARCH_SERVICE_BASE_URI
                      valueFrom:
                          secretKeyRef:
                              name: commonurl
                              key: FDK_SEARCH_SERVICE_BASE_URI
                    - name: FDK_RESOURCE_SERVICE_BASE_URI
                      valueFrom:
                          secretKeyRef:
                              name: commonurl
                              key: FDK_RESOURCE_SERVICE_BASE_URI
                    - name: FDK_MQA_API_BASE_URI
                      valueFrom:
                          secretKeyRef:
                              name: commonurl
                              key: FDK_MQA_API_BASE_URI
                    - name: DIGDIR_ORGLOGO_API_BASE_URI
                      valueFrom:
                          secretKeyRef:
                              name: commonurl
                              key: DIGDIR_ORGLOGO_API_BASE_URI
                    - name: ACCESS_REQUEST_API_HOST
                      valueFrom:
                          secretKeyRef:
                              name: commonurl
                              key: ACCESS_REQUEST_API_HOST
                    - name: FDK_DATASET_PREVIEW_API_KEY
                      valueFrom:
                          secretKeyRef:
                              name: fdk-dataset-preview-service
                              key: API_KEY
                    - name: FDK_SPARQL_ENDPOINT
                      valueFrom:
                          secretKeyRef:
                              name: commonurl
                              key: FDK_SPARQL_API_BASE_URI
                  image: data-norge-frontend
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
                  livenessProbe:
                      failureThreshold: 3
                      httpGet:
                          path: /api/ping
                          port: 8080
                          scheme: HTTP
                      periodSeconds: 30
                      successThreshold: 1
                      timeoutSeconds: 1
                      initialDelaySeconds: 20
                  readinessProbe:
                      failureThreshold: 3
                      httpGet:
                          path: /api/ping
                          port: 8080
                          scheme: HTTP
                      periodSeconds: 30
                      successThreshold: 1
                      timeoutSeconds: 1
                      initialDelaySeconds: 20
                  resources:
                      requests:
                          cpu: 50m
                          memory: 500Mi
                      limits:
                          memory: 500Mi
