---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forms-frontend
  labels:
    app: forms-frontend
spec:
  selector:
    matchLabels:
      app: forms-frontend
  template:
    spec:
      containers:
        - name: forms-frontend
          env:
            - name: FDK_USE_DEMO_LOGO
              value: "true"
            - name: DATAJEGER_EMAIL_ADDRESS
              value: datajegeren@norge.no
            - name: FDK_MAIL_SERVICE_ENDPOINT
              value: http://localhost:8081/api/sendmail
            - name: FDK_MAIL_SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: fdk-smtp-demo
                  key: API_KEY
            - name: FDK_REGISTRATION_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-demo
                  key: FDK_REGISTRATION_BASE_URI
            - name: FDK_COMMUNITY_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-demo
                  key: FDK_COMMUNITY_BASE_URI
            - name: FDK_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-demo
                  key: FDK_BASE_URI
