apiVersion: apps/v1
kind: Deployment
metadata:
    name: data-norge-frontend
    labels:
        app: data-norge-frontend
spec:
    selector:
        matchLabels:
            app: data-norge-frontend
    template:
        spec:
            containers:
                - name: data-norge-frontend
                  env:
                      - name: FDK_REGISTRATION_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-demo
                                key: FDK_REGISTRATION_BASE_URI
                      - name: FDK_COMMUNITY_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-demo
                                key: FDK_COMMUNITY_BASE_URI
                      - name: FDK_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-demo
                                key: FDK_BASE_URI
                      - name: DATAJEGER_EMAIL_ADDRESS
                        valueFrom:
                            secretKeyRef:
                                name: fdk-smtp-demo
                                key: DATAJEGER_EMAIL_ADDRESS
                      - name: FDK_MAIL_SERVICE_ENDPOINT
                        valueFrom:
                            secretKeyRef:
                                name: fdk-smtp-demo
                                key: FDK_MAIL_SENDER_SERVICE_ENDPOINT
                      - name: FDK_MAIL_SERVICE_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: fdk-smtp-demo
                                key: API_KEY
                      - name: FDK_LLM_SEARCH_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-demo
                                key: FDK_LLM_SEARCH_BASE_URI
                      - name: FDK_SEARCH_SERVICE_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-demo
                                key: FDK_SEARCH_SERVICE_BASE_URI
                      - name: FDK_RESOURCE_SERVICE_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-demo
                                key: FDK_RESOURCE_SERVICE_BASE_URI
                      - name: FDK_MQA_API_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-demo
                                key: FDK_MQA_API_BASE_URI
                      - name: DIGDIR_ORGLOGO_API_BASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-demo
                                key: DIGDIR_ORGLOGO_API_BASE_URI
                      - name: ACCESS_REQUEST_API_HOST
                        valueFrom:
                            secretKeyRef:
                                name: commonurl-demo
                                key: ACCESS_REQUEST_API_HOST
