---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: details-frontend
    labels:
        app: details-frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: details-frontend
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: details-frontend
            annotations:
                prometheus.io/scrape: 'false'
        spec:
            containers:
                - name: details-frontend
                  image: details-frontend
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
                  livenessProbe:
                      failureThreshold: 3
                      httpGet:
                          path: /api/ping
                          port: 8080
                          scheme: HTTP
                      periodSeconds: 30
                      successThreshold: 1
                      timeoutSeconds: 1
                      initialDelaySeconds: 20
                  readinessProbe:
                      failureThreshold: 3
                      httpGet:
                          path: /api/ping
                          port: 8080
                          scheme: HTTP
                      periodSeconds: 30
                      successThreshold: 1
                      timeoutSeconds: 1
                      initialDelaySeconds: 20
                  resources:
                      requests:
                          cpu: 50m
                          memory: 500Mi
                      limits:
                          memory: 500Mi
